// EasyPlayerWebActiveX.idl : ActiveX 控件项目的类型库源。

// 此文件将由 MIDL 编译器工具处理以
// 产生类型库(EasyPlayerWebActiveX.tlb)，该类型库将成为
// EasyPlayerWebActiveX.ocx.

#include <olectl.h>
#include <idispids.h>

[ uuid(E7319905-7F58-422D-9AF6-292078B85D1C), version(1.0),
  control ]
library EasyPlayerWebActiveXLib
{
	importlib(STDOLE_TLB);

	//  CEasyPlayerWebActiveXCtrl 的主调度接口
	[ 
		uuid(FB5E35A6-2538-47C4-9B40-B0FB6A00DEA0)	
	]
	dispinterface _DEasyPlayerWebActiveX
	{
		properties:
		methods:

			[id(DISPID_ABOUTBOX)] void AboutBox();
			[id(1)] LONG Start(BSTR sURL, BSTR sRenderFormat, BSTR sUserName, BSTR sPassword);
			[id(2)] void Config(BSTR sFrameCache, BSTR sPlaySound, BSTR sShowToScale, BSTR sShowStatisticInfo);
			[id(3)] void Close(void);
	};

	//  CEasyPlayerWebActiveXCtrl 的事件调度接口

	[ 
		uuid(66887A6D-C75B-48B8-B5E1-BD722D875923)	
	]
	dispinterface _DEasyPlayerWebActiveXEvents
	{
		properties:
			//  事件接口没有任何属性

		methods:
	};

	//  CEasyPlayerWebActiveXCtrl 的类信息
	[
		uuid(1EE1C648-F4A9-42F9-9AA7-2C8E3AF7B7FD), licensed
	]
	coclass EasyPlayerWebActiveX
	{
		[default] dispinterface _DEasyPlayerWebActiveX;
		[default, source] dispinterface _DEasyPlayerWebActiveXEvents;
	};

};
